name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and package
      run: npm run pack

    - name: Get version from package.json
      id: get-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release v${{ steps.get-version.outputs.version }}
        body: |
          ## Changes

          - 自动构建和打包 Tabby Compnet Lab Helper v${{ steps.get-version.outputs.version }}

          ## Installation

          下载 `tabby-compnet-lab-helper-v${{ steps.get-version.outputs.version }}.zip` 并安装到 Tabby 中。
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./tabby-compnet-lab-helper-v${{ steps.get-version.outputs.version }}.zip
        asset_name: tabby-compnet-lab-helper-v${{ steps.get-version.outputs.version }}.zip
        asset_content_type: application/zip
