name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and package
      run: npm run pack

    - name: Get version from package.json
      id: get-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release v${{ steps.get-version.outputs.version }}
        body: |
          ## Changes

          - 自动构建和打包 Tabby Compnet Lab Helper v${{ steps.get-version.outputs.version }}

          ## Installation

          下载 `tabby-compnet-lab-helper-v${{ steps.get-version.outputs.version }}.zip` 并安装到 Tabby 中。
        draft: false
        prerelease: false
        files: ./tabby-compnet-lab-helper-v${{ steps.get-version.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
